### ISSUE TITLE
Exposed registry.connect.redhat.com credentials

### ISSUE THREAD

**Issue by rht-lhajn** [fgiloux/auto-perf-test#2]
Hello,

We've received a report we'd like to bring your attention to. It appears this repository contains credentials for registry.connect.redhat.com among other credentials:

https://github.com/fgiloux/auto-perf-test/blob/16e140c6c042841e5aa837ff4ee5c6310352e8f9/jmeter/openshift/registry-secret.yaml#L3

Best regards

**Comment by fgiloux** [comment]
the file has been removed from history.
